# Generated by Django 3.1.5 on 2021-03-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('lecture_no', models.PositiveIntegerField()),
                ('lecture_na', models.CharField(max_length=100)),
                ('pdf', models.CharField(max_length=100)),
                ('ppt', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=100)),
            ],
        ),
    ]
