# Generated by Django 3.1.5 on 2021-03-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='word',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
